- name: vars preference
  hosts: local
  connection: local
  vars:
    NAME: from play level
  vars_files:
  - course.yaml
  vars_prompt:
  - name: NAME
    prompt: What is your NAME?
    private: false
  tasks:
  - name: testing variables preference
    # vars: 
    #   NAME: from task level
    ansible.builtin.debug:
      msg: "Name: {{ NAME }}"

      #1. first prefernece is args or command line? command line
      #2.from prompt