- name: conditions
  hosts: local
  connection: local
  vars:
  	number: 12
  tasks:
  - name: check number is less than 10 or no
    ansible.builtin.debug:
      msg: "Given numger {{ number }} is less than 10"
    when: number < 10