- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.biultin.debug:
      msg: "Hello {{ item }}" #item is reserved
    loop:
    - Jeeva
    - Sivakumar
    - Sree 
    - Prakruthi
    - Sai 
